#!/usr/bin/env python3
"""Generate self-contained model resolution assets from the kit's maintained sources."""

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ("independent-review", "docs-maintenance")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    script = (ROOT / "scripts/resolve-agent-model.py").read_text()
    script = script.replace("#!/usr/bin/env python3\n", "#!/usr/bin/env python3\n# Generated by scripts/sync-model-resolver.py; edit the kit source, not this copy.\n", 1)
    settings = "# Generated from kit agent-settings.env; do not edit this copy.\n" + "\n".join(
        line for line in (ROOT / "agent-settings.env").read_text().splitlines()
        if line.startswith(("REVIEW_MODEL_", "REVIEW_REQUIRE_OTHER_LINEAGE=", "WRITING_MODEL_DEEP="))
    ) + "\n"
    mismatches = []
    for skill in SKILLS:
        root = ROOT / "skills" / skill
        for relative, content in (("scripts/resolve-agent-model.py", script), ("references/model-defaults.env", settings)):
            path = root / relative
            if args.check:
                if not path.is_file() or path.read_text() != content:
                    mismatches.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    if mismatches:
        print("Generated model assets are stale; run python3 scripts/sync-model-resolver.py:\n" + "\n".join(mismatches))
        return 1
    print("PASS: model resolution assets " + ("match sources" if args.check else "generated"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
